services:
  - type: web
    name: chat-with-pdf
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=10000 --server.address=0.0.0.0"
    pythonVersion: 3.11.11
